# Generated by Django 4.2.4 on 2023-08-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comment_listing_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="comments",),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
