# Generated by Django 4.2.4 on 2023-08-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_listing_comments_comment_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="watchlist",),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(blank=True, to="auctions.listing"),
        ),
    ]
