# Generated by Django 4.2.4 on 2023-09-06 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_category_rename_buyer_listing_winner_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="price",),
        migrations.AddField(
            model_name="bid",
            name="date_created",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="myBid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allBids",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="myListings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="myWatchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
